### ISSUE TITLE
Rename project to Squid

### ISSUE THREAD

**Issue by SirRade** [ink-markup/ink#17]
[These dudes](https://github.com/sapo/Ink) had the name first. They use the same file extension and are also a markup language.

Squid is thematically similar and [not used for any language related projects](https://github.com/search?utf8=%E2%9C%93&q=squid&type=).  
I propose to switch to the extension .sq, as it is [not used by anyone yet](https://github.com/search?utf8=%E2%9C%93&q=extension%3A.sq&type=Code&ref=advsearch&l=&l=).

Plus, we get to use this cute emoji: 🦑

**Comment by bash** [comment]
**TODO:**

- [ ] Rename organisation to `squid-lang`
- [ ] Rename npm organisation
- [ ] Fix travis and codecov badges
- [ ] 🦑

**Comment by bash** [comment]
✅ Just got confirmation that the npm org `@ink-markup` has been deleted
